name: Cypress Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome96-ff94
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          record: false
          browser: chrome
          headless: true
          spec: cypress/integration/smoke/**/*.spec.js
