name: Cypress Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.13.0-chrome95-ff94
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          record: false
          video: false
          screenshots: false
          browser: chrome
          headless: true
          spec: cypress/integration/smoke/**/*.spec.js
